include_configs:
  - ../train/diffusion/diffusion_16x16x16_dense.yaml
  - dales2.yaml

name: 'dales2/diffusion_dense'

vae_config: "configs/dales2/train_vae_32x32x32_dense.yaml"
vae_checkpoint: "checkpoints/dales2/coarse_vae/last.ckpt"

# adjust data setting
voxel_size: 5 
crop_size: 100
resolution: 20

# adjust network
network:
  diffuser:
    image_size: 32 # use during testing
    attention_resolutions: [2, 4, 8]